export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const CLEAR_CART = 'CLEAR_CART';
export const SET_PAYMENT_INFO = 'SET_PAYMENT_INFO';
export const SET_ADDRESS_INFO = 'SET_ADDRESS_INFO';