export const ADD_TO_CART = "ADD_TO_CART";
export const SET_PAYMENT = "SET_PAYMENT";
export const SET_ADDRESS = "SET_ADDRESS";
export const DECREMENT_CART_ITEM = "DECREMENT_CART_ITEM";
export const TOGGLE_CHECK_ITEM = "TOGGLE_CHECK_ITEM";
export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";
export const CLEAR_SHOPPING_CART = "CLEAR_SHOPPING_CART";